name: update-cache

on:
  push:
    branches:
      - "main"

jobs:
  build-cache:
    name: Build Cache
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip  # Cache pip cache instead of the entire Python installation
          key: ${{ runner.os }}-pip-${{ hashFiles('.config/requirements.txt') }} }}
          restore-keys:
            - ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .config/requirements.txt

      - name: Save Cache State # This step is crucial for correct caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache Miss - Saving Cache State"
          # No explicit action needed here, the cache action automatically saves the updated cache.
          # This step primarily serves to log that a cache miss occurred.

      - name: Load Cache State # This step is crucial for using the cache effectively
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "Cache Hit - Loading Cache State"
          # No explicit action needed here, the cache action automatically restores the cache.
          # This step primarily serves to log that a cache hit occurred.
